version: '3.7'
services:
  server:
    container_name: python_devserver
    image: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_PORT=8080
