version: '3.7'
services:
  server:
    container_name: python_devserver
    image: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_PORT=8080
    links:
      # network connection with these services
      - mysql
    depends_on:
      # build those images first
      - mysql

  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
        # pass volume named mysql-data to mysql container
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
    # <Port exposed> : <MySQL Port running inside container>
      - "3307:3306"
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql

# volumes definition here
volumes:
  # just a persistance data
  mysql-data:
    driver: local